### ISSUE TITLE
히스토리 목록 API 연결

### ISSUE THREAD

**Issue by hj1115hj** [mash-up-kr/TwoToo_Android#132]
# ✅ ISSUE FEATURE

## Title 
- 히스토리 목록 API 연결

## Description from Title
- 히스토리 목록 API 연결

## Todo
- [ ] 레파지토리 api 만들기
- [ ] 도메인 모델 만들기
- [ ] usecase 만들고 viewModel 연결하기
