### ISSUE TITLE
온보딩 ~ 챌린지 생성까지 BUG 수정

### ISSUE THREAD

**Issue by ddyeon** [mash-up-kr/TwoToo_Android#180]
# 🐞 ISSUE BUG

## Title
- 온보딩 ~ 챌린지 생성까지 BUG 수정

## Description From Title
추가예정

## Todo
- [x] 꽃 선택화면 일부 기기에서 스크롤 문제
- [x] 챌린지 카드 투투챌린지 글씨 width 작을 때 잘리는 현상
- [x] 챌린지 생성 뒤로가기 시 content 사라지는 이슈
