### ISSUE TITLE
새로운 홈 디자인 소스 적용

### ISSUE THREAD

**Issue by 014967** [mash-up-kr/TwoToo_Android#87]
# 🔍 ISSUE REFACTOR

## Title 
- design system 새로운 이미지 적용

## Description from Title(Optional)
- design system 새로운 이미지 적용

## Todo(Optional)
- [ ] 새로운 이미지 적용
- [ ] 이미지를 통해서, 모델 변경 
- [ ] 이미지 변경으로 인한, 코드 수정
